version: '3.3'
services:
  apiservice:
    build: ../.
    depends_on:
      postgressrv:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - fa_db_serv=postgressrv
      - 'fa_db_user=${USUARIO}'
      - 'fa_db_pass=${SENHA}'
      - 'fa_db_data=${BANCO}'
  postgressrv:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=${SENHA}'
      - 'POSTGRES_USER=${USUARIO}'
      - 'POSTGRES_DB=${BANCO}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - '/home/ubuntu/data:/var/lib/postgresql/data'