version: '3.3'
services:
  apiservice:
    build: ../.
    depends_on:
      - postgressrv
    ports:
      - '80:80'
      - '443:443'
    environment:
      - 'fa_db_serv=${SERVIDOR}'
      - 'fa_db_user=${USUARIO}'
      - 'fa_db_pass=${SENHA}'
      - 'fa_db_data=${BANCO}'
  postgressrv:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=${SENHA}'
      - 'POSTGRES_USER=${USUARIO}'
      - 'POSTGRES_DB=${BANCO}'
    volumes:
      - '/home/ubuntu/data:/var/lib/postgresql/data'